# Generated by Django 5.2.13 on 2026-06-12 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, help_text='Short tagline/summary', max_length=500)),
                ('about', models.TextField(blank=True, help_text='Detailed description of the city')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='cities/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.city')),
            ],
            options={
                'verbose_name': 'City Photo',
                'verbose_name_plural': 'City Photos',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceToVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('distance', models.CharField(blank=True, help_text='e.g., 2 km from hotel', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='properties.city')),
            ],
            options={
                'verbose_name': 'Place to Visit',
                'verbose_name_plural': 'Places to Visit',
                'ordering': ['order', 'name'],
            },
        ),
    ]
