# Generated by Django 5.2.13 on 2026-08-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_phones_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('flat', 'Flat Amount (₹)'), ('percentage', 'Percentage (%)')], help_text='Leave blank for no discount', max_length=10),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flat amount in ₹, or a percentage from 0-100, depending on the discount type above', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='offer_name',
            field=models.CharField(blank=True, help_text='e.g., Diwali Offer', max_length=200),
        ),
    ]
